"""Project defaults and payload key constants."""

SSID_KEY = "ssid"
PASSWORD_KEY = "pwd"

STATUS_STANDBY = "Standby"
STATUS_CONNECTING = "Connecting"
STATUS_SUCCESS_PREFIX = "Success_IP:"
STATUS_FAIL_PREFIX = "Fail:"
STATUS_BUSY_PREFIX = "Busy:"

DEFAULT_DEVICE_NAME = "Orin_Drone_01"
DEFAULT_SCAN_TIMEOUT = 20
DEFAULT_WAIT_TIMEOUT = 45
DEFAULT_CONNECT_TIMEOUT = 40
