[package]
name = "yundrone-ble-server"
version.workspace = true
edition.workspace = true

[lib]
name = "server"

[[bin]]
name = "yundrone-ble-server"
path = "src/main.rs"

[dependencies]
protocol = { path = "../protocol" }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
thiserror = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }

[target.'cfg(target_os = "linux")'.dependencies]
async-trait = "0.1"
bluer = { version = "0.17", features = ["bluetoothd"] }
futures = "0.3"
tokio-stream = "0.1"
uuid = "1.0"
